M48
; DRILL file {KiCad 7.0.6} date Sun Mar 24 10:59:27 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-24T10:59:27+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.1709Y-3.5031
T1
G00X5.1709Y-3.7807
M15
G01X5.1709Y-3.7925
M16
G05
T0
M30
